export const CryptidState =  [
    {
        title: "50ft Congo Snake",
        topic: "Snake",
        mainImg: TBD,
        secondaryImg: TBD,
        url: "/cryptids/:id",
        first_sighting: 1959,
        last_sighting: "Unknown",
        continent:"South America",
        country: "Democratic Republic of Congo",
        sighting_location: "Unexplored rainforests of the Congo",
        source: "https://mysteriesrunsolved.com/2020/05/the-congo-snake.html",
        description:"In 1959, Remy Van Lierde served as a Colonel in the Belgian Air Force at the Kamina airbase in Belgian occupied Congo. In the Katanga region of the Democratic Republic of the Congo, returning from a mission by helicopter, he reported having seen an enormous snake as he flew over the forests. He described the snake as being close to 50 feet in length, with a 2 foot wide by 3 feet long triangular head, which, if his estimations were accurate, would earn the creature a place amongst the largest snakes to have ever existed. Colonel Van Lierde described the snake as having dark green and brown top scales and a white-ish colored underside. Upon sighting the reptile, he had the pilot turn around and make another pass. at which the serpent reared up the frontal ten feet of its body head as if to strike, giving him the opportunity to observe its underbelly. However, after flying so low that Van Lierde believed it to have been within striking distance of his helicopter, he ordered the pilot to resume his journey, and so the creature was never properly documented, although some reports suggest that an onboard photographer managed to snap a shot of it. It is believed to be either a massively oversized African rock python, a new species of snake entirely, or perhaps a descendant of the giant Eocene snake Gigantophis."  
    },
    {
        title: "Abominable snowman (Also known as Yeti)",
        topic: "Bigfoot",
        mainImg: TBD,
        secondaryImg: TBD,
        url: "/cryptids/:id",
        first_sighting: 1832,
        last_sighting: "2019",
        continent: "Asia, North America",
        country: "Tibet",
        sighting_location: "Mountian ranges in variouis countries",
        source: "https://cryptidz.fandom.com/wiki/Yeti#Sightings",
        description:"The Yeti, also known as the Abominable Snowman, is an Asian Bigfoot found in the Himalayas. Inhabiting Nepal, Tibet, Russia, and India, the Yeti is probably the closest living relative to Gigantopithecus, a prehistoric ape that lived in Asia three hundred thousand years ago.In Buddhist mythology, the Yetis were peaceful creatures, that were very shy, and lived in dense snow caves on the glaciers which form the Ganges River in India. In modern times, most sightings and evidence are on K2. The name Yeti derives from Yeh-Tah, meaning rock thing.The Yeti was even mentioned in pre-Buddhist cultures, such as the Lecha people, who worshiped a Glacier Giant. Tibetan and Nepalese monasteries have collected several skulls and bones of the yetis, some which preside in the Smithsonian Museum today. Although one of their specimens was proven to be a human bone, others contained the museum are still in question.Yetis according to Twenty-First Century sightings are said to stand from 8 to 10.5 feet tall, have a furry coat of brown, reddish or black hair and to resemble a huge, upright walking ape. Contrary to popular misconception the yeti is not white. The photograph in the gallery below said to be a 'white coated yeti' is in fact a picture of 'Snowflake' the albino gorilla that once lived at Barcelona Zoo. There have been no reports of white yeti in reality. Several expeditions have taken place to find the Yetis, however, only footprints, bones, and hair samples have been  discovered.Yetis have been sighted in the Himalayas since 6th BCE to 2019. It is the oldest recorded Bigfoot, or hairy hominid."  
    },
    {
        title: "Baba yaga",
        topic: "Folklore",
        mainImg: TBD,
        secondaryImg: TBD,
        url: "/cryptids/:id",
        first_sighting: "Unknown",
        last_sighting: "Unknown",
        continent: "Asia, Europe",
        country: "Russia",
        sighting_location: "N/a",
        source: "https://cryptidz.fandom.com/wiki/Baba_Yaga",
        description:"In Slavic Folklore (mostly in Russia, but also in Croatia, Poland, Serbia etc.), the Baba Yaga (Russian: Баба-яга; Baba Jaga) is a supernatural being or witch that takes the form of a hideous old woman.Baba Yaga is usually described as wearing a cloak or dress, with bright red eyes and teeth of sharpened stone or metal. It is said that she lives in a hut deep in the woods that stands on chicken legs (or one chicken leg), surrounded by a fence of bones taken from her victims, and that she flies around in a mortar wielding a pestle.There are sometimes shown to be three Baba Yagas, who are sisters. In those cases, they all have the same name."  
    },
    {
        title: "Baron Samdei",
        topic: "Gods",
        mainImg: TBD,
        secondaryImg: TBD,
        url: "/cryptids/:id",
        first_sighting: "Unknown",
        last_sighting: "Unknown",
        continent: "North America",
        country: "Hatia",
        sighting_location: "N/a",
        source: "https://en.wikipedia.org/wiki/Baron_Samedi",
        description:"Baron Samedi (English: Baron Saturday), also written Baron Samdi, Bawon Samedi or Bawon Sanmdi, is one of the loa of Haitian Vodou. He is a loa of the dead, along with Baron's numerous other incarnations Baron Cimetière, Baron La Croix and Baron Criminel. He is syncretized with Saint Martin de Porres.He is the head of the Gede family of loa; his brothers are Azagon Lacroix and Baron Piquant and he is the husband of Maman Brigitte. Together, they are the guardians of the past, of history and, heritage. Baron Samedi is usually depicted with a top hat, black tail coat, dark glasses, and cotton plugs in the nostrils, as if to resemble a corpse dressed and prepared for burial in the Haitian style. He is frequently depicted as a skeleton (but sometimes as a black man that merely has his face painted as a skull), and speaks in a nasal voice. The former President-for-Life of Haiti, François Duvalier, known as Papa Doc, modeled his cult of personality on Baron Samedi; he was often seen speaking in a deep nasal tone and wearing dark glasses.He is noted for disruption, obscenity, debauchery, and having a particular fondness for tobacco and rum. Additionally, he is the loa of resurrection, and in the latter capacity he is often called upon for healing by those near or approaching death, as it is only the Baron that can accept an individual into the realm of the dead.Baron Samedi spends most of his time in the invisible realm of vodou spirits. He is notorious for his outrageous behavior, swearing continuously and making filthy jokes to the other spirits. He is married to another powerful spirit known as Maman Brigitte, but often chases after mortal women. He loves smoking and drinking and is rarely seen without a cigar in his mouth or a glass of rum in his bony fingers. Baron Samedi can usually be found at the crossroads between the worlds of death and the living. When someone dies, he digs their grave and greets their soul after they have been buried, leading them to the underworld"  
    },
    {
        title: "Bigfoot",
        topic: "Bigfoot",
        mainImg: TBD,
        secondaryImg: TBD,
        url: "/cryptids/:id",
        first_sighting: "Up to 1,000,000 years ago",
        last_sighting: "Present",
        continent: "All",
        country: "All",
        sighting_location:"Remote lush forests in mountainous regions of the world",
        source: "https://cryptidz.fandom.com/wiki/Bigfoot",
        description:"A Bigfoot is a heavy, bipedal humanoid ape. It is believed that Bigfoot stands at around eight to ten feet tall--however the Hibagon stands at only four to five feet--and has long arms. It has dense fur, ranging in colors from red, to white, to brown. It has very large feet, which is why it is called Bigfoot. Some people believe that Bigfoot is the descendant of the prehistoric giant orangutan Gigantopithecus, whereas others think it descended from prehistoric homininds such as a Neanderthal Man or Australopithecus. Some sightings of Bigfoot can be traced back to bears"  
    },
    {
        title: "El Chupacabra",
        topic: "Animalistic",
        mainImg: TBD,
        secondaryImg: TBD,
        url: "/cryptids/:id",
        first_sighting: "March 1995",
        last_sighting: "2013",
        continent: "North America",
        country: "Puerto Rico, United States, Mexico, Paraguay",
        sighting_location: "Remote Deserts in Southwestern North America, and jungles of Puerto Rico",
        source: "https://cryptidz.fandom.com/wiki/Chupacabra",
        description:"Their first known attacks were in March of 1995 in Puerto Rico. Eight sheep were discovered dead, each completely drained of blood. Investigators found three strange puncture wounds in the chests of the animals. Despite the odd circumstances, authorities could only attribute the killings to a known predator - a fox, perhaps. Others, however, recognized the similarities in these deaths to the enigmatic cattle mutilations which had been taking place in the American southwest with increasing regularity. The woman who first sighted the monster, Madelyne Tolentino, had an eyewitness description was the basis for the most famous drawing of the chupacabra in the world. In Canóvanas, about 30 citizens claimed to have seen the chupacabras, swearing that it had swooped down from the sky and leapt over treetops. It wasn't until November, 19, 1995 that a detailed description of chupacabras came from an eyewitness. On that autumn night in Puerto Rico, the creature struck again. Farmers awoke to a horrifying scene: dozens of turkeys, rabbits, goats, cats, dogs, horses and cows... dead, with no explainable cause. Just the mysterious markings left by the blood-drinking chupacabras.But in the north-central city of Caguas, a startled homeowner caught the world's first fleeting glimpse of the goat sucker. Described as having huge red eyes and hairy arms, the creature allegedly broke into the bedroom of the house through a window, tore apart a child's stuffed Teddy bear, and left a puddle of slime and a single piece of rancid meat on the windowsill before disappearing. "  
    },
    {
        title: "Jersey Devil",
        topic: "Animalistic",
        mainImg: TBD,
        secondaryImg: TBD,
        url: "/cryptids/:id",
        first_sighting: "1735",
        last_sighting: "2009",
        continent: "North America",
        country: "United States",
        sighting_location:"New Jersey",
        source: "https://cryptidz.fandom.com/wiki/Jersey_Devil",
        description:"The Jersey Devil is a creature native to the Pine Barrens of New Jersey. It is often described as having hooves, a snake's tail, bat-wings and a head that looks something like a horse. While there are many stories detailing the origin of the Jersey Devil, sightings have been reported beginning in the 1700s and continuing on until the past decade. The creature is deeply rooted in folklore and legend in the area, and is still mildly popular in various media, from sports teams to video games. This Jersey Devil often glows, and it can breathe fire or poison water with its breath, both classic dragon characteristics. The Jersey Devil of folklore is also known as the Leeds Devil. Local residents trace its origin to a woman named Mother Leeds, the mistress of a British soldier who was suspected of being a witch. When she gave birth to her thirteenth child, she cursed it. The baby was born as a hairy creature and soon took to terrorizing the populace and eating children."  
    },
    {
        title: "Lizard Man of Scape Ore Swamp",
        topic: "Animalistic",
        mainImg: TBD,
        secondaryImg: TBD,
        url: "/cryptids/:id",
        first_sighting: "1987",
        last_sighting: "2011",
        continent: "North America",
        country: "United States",
        sighting_location:"	Remote Swamps, Bogs and drainage pipes",
        source: "https://cryptidz.fandom.com/wiki/Lizard_Man_of_Scape_Ore_Swamp",
        description:"Many theories have been presented in relation to the identity of Lizard Men, theories such as living dinosaurs, and even offshoots of evolution in which the reptilian hierarchy continued to evolve along the same path as early primates. At one point in time reptiles ruled the earth, it is not out of the realm of possibility that the most dominate species on the planet could continue to evolve in small numbers unseen by mankind. Although no reptilian species known to man have shown signs of such advanced evolution, the reptile is the oldest and most successful species on the planet and could hold secrets that have yet to come to light. In Lee County, South Carolina, a strange reptilian humanoid was reported on several accounts."  
    },
    {
        title: "Momo",
        topic: "Bigfoot",
        mainImg: TBD,
        secondaryImg: TBD,
        url: "/cryptids/:id",
        first_sighting: "1971",
        last_sighting: "1972",
        continent: "North America",
        country: "United States",
        sighting_location:"Missouri",
        source: "https://cryptidz.fandom.com/wiki/Momo",
        description:"Momo is the name of a local legend, similar to the Bigfoot, which is reported to live in Missouri. The name Momo is short for Missouri Monster and it is reported to have a large, pumpkin-shaped head, with a very furry body, and hair covering the eyes.First reported in July 1971, near Louisiana, Missouri by Joan Mills and Mary Ryan, Momo has been spotted up and down the Mississippi River. It is supposedly a large, 7 ft (~2.1 m) tall, hairy, black, manlike creature that eats dogs and emits a terrible odor. Some suggest it was a rogue black bear. Following sightings in 1972 beginning at 3:30 p.m. July 11, first reported by Terry, Wally, and Doris Harrison, and lasting for about 2 weeks, tracks were found and submitted to Lawrence Curtis, director of the Oklahoma City Zoo and Botanical Garden. He deemed the tracks to be a hoax."  
    },
    {
        title: "Mothman",
        topic: "Animalistic",
        mainImg: TBD,
        secondaryImg: TBD,
        url: "/cryptids/:id",
        first_sighting: "1971",
        last_sighting: "1972",
        continent: "North America",
        country: "United States",
        sighting_location:"	Point Pleasant, West Virginia",
        source: "https://cryptidz.fandom.com/wiki/Mothman",
        description:"The state of West Virginia has had its fair share of strange and often inexplicable events such the visitation of the Flatwoods Monster and Indrid Cold, but perhaps the strangest yet is the arrival of the creature known as the Mothman, who changed the sleepy little town of Point Pleasant forever when it swooped in one cold autumn night in 1966.Today, Mothman is one of the most well-known cryptids in the world, made famous partly by John Keel's book (later adapted to film) The Mothman Prophecies. Mothman is also hunted in Mountain Monsters on Destination America.The first recorded Mothman sighting took place on November 12, 1966, near Clendenin, West Virginia.Five men were in a cemetery preparing a grave for burial when they saw something they couldn't explain. Lifting off from the nearby trees was a brown winged creature. The men held to the fact that what lifted off beyond the trees was no bird; it was a humanoid."  
    },
    {
        title: "Nessie (or Loch Ness Monster)",
        topic: "Aquatic",
        mainImg: TBD,
        secondaryImg: TBD,
        url: "/cryptids/:id",
        first_sighting: "AD 565",
        last_sighting: "2018",
        continent: "Europe",
        country: "Scotland",
        sighting_location:"Loch Ness",
        source: "https://cryptidz.fandom.com/wiki/Loch_Ness_Monster",
        description:"The Loch Ness monster, also known by the nickname Nessie, is probably the creature that most often leaps to mind when ordinary people think about cryptozoology: the study of animals that may or may not exist. Nessie is virtually a symbol of cryptozoology. This creature has probably been the object of more sustained media attention than any other individual type of cryptid, with the possible exception of Sasquatch, and some less traditional cryptids such as the Grey Aliens.Witnesses tend to describe an animal with sleek, rubbery blackish-gray skin, about twenty feet long. Nessie usually has the serpentine body that is typical for sea serpents and lake monsters, furnished with humps along its length, and one or more sets of paddles (or sometimes, stumpy legs). Nessie's head is often described as roughly horse-shaped, it may have a straggly mane running down its neck, and some witnesses report small horns or a crest, especially those who see the Loch Ness monster from close up. Sometimes, witnesses report a smaller, rounded, turtle-like head. This head is the one that seems to appear in most of the famous Nessie photos."  
    },
    {
        title: "Ohio frogman (Loveland Frogmen)",
        topic: "Aquatic",
        mainImg: TBD,
        secondaryImg: TBD,
        url: "/cryptids/:id",
        first_sighting: "1955",
        last_sighting: "2016",
        continent: "North America",
        country: "United States",
        sighting_location:"Ohio",
        source: "https://cryptidz.fandom.com/wiki/Loveland_Frogmen",
        description:"The Loveland frogmen, also known as the Loveland lizards, are cryptids who derive their name from the area they inhabit, nearby Loveland, Ohio. The creatures themselves have been sighted in Clermont County.The Loveland frogmen are bipedal frogs as made evident due to their leathery skin as well as their webbed hands and feet. The creatures have frog-like heads with wrinkly skin on top of them. They are around 1 meter tall.These amphibious anomalies have shocked and terrified both businessmen, farmers and police officers and remain one of the most intriguing cryptozoological mysteries in the United States.One of the most intriguing cases encountered is that of the Loveland Frogmen, or Loveland Lizards. The story of these unique creatures begins in May of 1955, on a lonely stretch of road that runs along the Miami River in Clermont County, just on the outskirts of a small town known as Loveland, Ohio.At approximately 3:30 a.m., an un-named business man claimed to have witnessed three, bipedal, quasi-reptilian entities congregating by the side of the road. The man pulled his car to the curb and observed these creatures for what he estimated to be about three minutes.During this time he noticed that these strange beings stood between 3 and 4-feet tall, were covered with leathery skin, and had webbed hands and feet. Their most distinguishing characteristic, however, was their distinctly “frog-like” heads, which the man claimed bore deep wrinkles where their hair should have been.Just as the man was about to steal away, one of the creatures suddenly held what the witness could only describe as a “wand” above its head. The anonymous source further claimed that sparks spewed out of the end of this device. He left posthaste. "  
    },
    {
        title: "Pope lick monster",
        topic: "Bigfoot && Animalistic",
        mainImg: TBD,
        secondaryImg: TBD,
        url: "/cryptids/:id",
        first_sighting: "1980",
        last_sighting: "Present day",
        continent: "North America",
        country: "United States",
        sighting_location:"Louisville, Kentucky",
        source: "https://cryptidz.fandom.com/wiki/Pope_Lick_Monster",
        description:"The Pope Lick Monster is a legendary part-man, part-goat or sometimes part-sheep creature reported to live beneath a Norfolk Southern Railroad trestle over Floyd's Fork Creek, in the Fisherville area near Louisville, Kentucky.In most accounts, the Pope Lick Monster (named after the Pope Lick Creek below the Pope Lick Train Trestle) appears as a human-goat hybrid with a grotesquely deformed body of a man. It has powerful, fur-covered goat legs, an alabaster-skinned face with an aquiline nose and wide set eyes. Short, sharp horns protrude from the forehead, nestled in long greasy hair that matched the color of the fur on the legs. Numerous urban legends exist about the creature's origins and the methods it employs to claim its victims. According to some accounts, the creature uses either hypnosis or voice mimicry to lure trespassers to the tressle to meet their death before an oncoming train. Other stories claim the monster jumps down from the trestle onto the roofs of cars passing beneath it. Yet other legends tell that it attacks its victims with a blood-stained ax. It has also been said that the very sight of the creature is so unsettling that those who see it while walking across the high trestle are driven to leap off.Other legends explain the creature's origins, including that it is a human-goat hybrid, and that it was a circus freak who vowed revenge after being mistreated. In one version, the creature escaped after a train derailed on the trestle which actually links the Pope Lick Monster to the legend of the Ghost Train which as also sighted on the trestle. Another version claims that the monster is really the twisted reincarnation of a farmer who sacrificed goats in exchange for Satanic powers. "  
    },
    {
        title: "South Carolina Thunderbird",
        topic: "Animalistic",
        mainImg: TBD,
        secondaryImg: TBD,
        url: "/cryptids/:id",
        first_sighting: "1989",
        last_sighting: "Present day",
        continent: "North America",
        country: "United States",
        sighting_location:"Pickens, South Carolina",
        source: "https://cryptidz.fandom.com/wiki/South_Carolina_Thunderbird",
        description:"In South Carolina, a white, orange eyed thunderbird has been reported to encounter drivers traveling throughout thestate. Reports of mysterious bird like creatures date back to the native americans of the region.The Wakinyan are thunderbirds. Kinyan is the Santee verb to fly and these creatures are represented as very mysterious and powerful birds. Dorsey records that the Santee believe that there are four different manifestations of the thunderbirds, which are the carriers of Wakinyan's power. In modern day South Carolina, there have been several sightings of pterosaur like thunderbirds.In 2013, a report surfaced of an encounter three years prior of a similar pterosaur like creature. It had leather-like wings and was almost as big across as the windshield. I did not get a good look because it was dark, but it had almost orange-reddish eyes and swooped up before it smashed into the windshield of the car. The whole time I was pumping the brakes afraid it was going the smash into the car. I told my parents but they tried to convince me it was a bat - but I told them no, it was way to big.Then one year later, my Dad told me he saw the same thing flying towards the windshield of his car on the same road and same spot. My Brother also saw it in the backyard as he was taking out scraps (phantomsandmonsters.com)."
    },
    {
        title: "The Wendigo",
        topic: "Animalistic",
        mainImg: TBD,
        secondaryImg: TBD,
        url: "/cryptids/:id",
        first_sighting: "40,000 years ago",
        last_sighting: "Present day",
        continent: "North America",
        country: "Canada",
        sighting_location:"Algonquin",
        source: "https://cryptidz.fandom.com/wiki/Wendigo",
        description:"The Wendigo (also known as the Windigo, Windago, Witiko, Wee-tee-go, Wihtikow, Waindigo and several other variants) is a cannibalistic spirit resembling a zombie. In some forms, the Wendigo is the size of a human, while in others, it can be fifteen-feet-tall. The earliest description of the Wendigo was that of similar appearance to a corpse, with a skeleton-like, thin body with gray skin, sunken eyes, bloody lips, yellow fangs and a long, slimy tongue. Later myths say that the Wendigo is a lipless ape with giant fangs that devours human flesh. It can turn a person into a Wendigo, which was one of the worst curses to the Algonquian-speaking Native Americans of Canada."
    },
]
