export const CryptidState =  [
    {
        title: "50ft Congo Snake",
        topic: "Snake",
        mainImg: TBD,
        secondaryImg: TBD,
        url: "/cryptids/:id",
        first_sighting: 1959,
        last_sighting: "Unknown",
        continent:"South America",
        country: "Democratic Republic of Congo",
        sighting_location: "Unexplored rainforests of the Congo",
        source: "https://mysteriesrunsolved.com/2020/05/the-congo-snake.html",
        description:"In 1959, Remy Van Lierde served as a Colonel in the Belgian Air Force at the Kamina airbase in Belgian occupied Congo. In the Katanga region of the Democratic Republic of the Congo, returning from a mission by helicopter, he reported having seen an enormous snake as he flew over the forests. He described the snake as being close to 50 feet in length, with a 2 foot wide by 3 feet long triangular head, which, if his estimations were accurate, would earn the creature a place amongst the largest snakes to have ever existed. Colonel Van Lierde described the snake as having dark green and brown top scales and a white-ish colored underside. Upon sighting the reptile, he had the pilot turn around and make another pass. at which the serpent reared up the frontal ten feet of its body head as if to strike, giving him the opportunity to observe its underbelly. However, after flying so low that Van Lierde believed it to have been within striking distance of his helicopter, he ordered the pilot to resume his journey, and so the creature was never properly documented, although some reports suggest that an onboard photographer managed to snap a shot of it. It is believed to be either a massively oversized African rock python, a new species of snake entirely, or perhaps a descendant of the giant Eocene snake Gigantophis."  
    },
    {
        title: "Abominable snowman (Also known as Yeti)",
        topic: "Bigfoot",
        mainImg: TBD,
        secondaryImg: TBD,
        url: "/cryptids/:id",
        first_sighting: 1832,
        last_sighting: "2019",
        continent: "Asia, North America",
        country: "Tibet",
        sighting_location: "Mountian ranges in variouis countries",
        source: "https://cryptidz.fandom.com/wiki/Yeti#Sightings",
        description:"The Yeti, also known as the Abominable Snowman, is an Asian Bigfoot found in the Himalayas. Inhabiting Nepal, Tibet, Russia, and India, the Yeti is probably the closest living relative to Gigantopithecus, a prehistoric ape that lived in Asia three hundred thousand years ago.In Buddhist mythology, the Yetis were peaceful creatures, that were very shy, and lived in dense snow caves on the glaciers which form the Ganges River in India. In modern times, most sightings and evidence are on K2. The name Yeti derives from Yeh-Tah, meaning rock thing.The Yeti was even mentioned in pre-Buddhist cultures, such as the Lecha people, who worshiped a Glacier Giant. Tibetan and Nepalese monasteries have collected several skulls and bones of the yetis, some which preside in the Smithsonian Museum today. Although one of their specimens was proven to be a human bone, others contained the museum are still in question.Yetis according to Twenty-First Century sightings are said to stand from 8 to 10.5 feet tall, have a furry coat of brown, reddish or black hair and to resemble a huge, upright walking ape. Contrary to popular misconception the yeti is not white. The photograph in the gallery below said to be a 'white coated yeti' is in fact a picture of 'Snowflake' the albino gorilla that once lived at Barcelona Zoo. There have been no reports of white yeti in reality. Several expeditions have taken place to find the Yetis, however, only footprints, bones, and hair samples have been  discovered.Yetis have been sighted in the Himalayas since 6th BCE to 2019. It is the oldest recorded Bigfoot, or hairy hominid."  
    },
    {
        title: "Baba yaga",
        topic: "Folklore",
        mainImg: TBD,
        secondaryImg: TBD,
        url: "/cryptids/:id",
        first_sighting: "Unknown",
        last_sighting: "Unknown",
        continent: "Asia, Europe",
        country: "Russia",
        sighting_location: "N/a",
        source: "https://cryptidz.fandom.com/wiki/Baba_Yaga",
        description:"In Slavic Folklore (mostly in Russia, but also in Croatia, Poland, Serbia etc.), the Baba Yaga (Russian: Баба-яга; Baba Jaga) is a supernatural being or witch that takes the form of a hideous old woman.Baba Yaga is usually described as wearing a cloak or dress, with bright red eyes and teeth of sharpened stone or metal. It is said that she lives in a hut deep in the woods that stands on chicken legs (or one chicken leg), surrounded by a fence of bones taken from her victims, and that she flies around in a mortar wielding a pestle.There are sometimes shown to be three Baba Yagas, who are sisters. In those cases, they all have the same name."  
    },
    {
        title: "Baron Samdei",
        topic: "Gods",
        mainImg: TBD,
        secondaryImg: TBD,
        url: "/cryptids/:id",
        first_sighting: "Unknown",
        last_sighting: "Unknown",
        continent: "North America",
        country: "Hatia",
        sighting_location: "N/a",
        source: "https://en.wikipedia.org/wiki/Baron_Samedi",
        description:"Baron Samedi (English: Baron Saturday), also written Baron Samdi, Bawon Samedi or Bawon Sanmdi, is one of the loa of Haitian Vodou. He is a loa of the dead, along with Baron's numerous other incarnations Baron Cimetière, Baron La Croix and Baron Criminel. He is syncretized with Saint Martin de Porres.He is the head of the Gede family of loa; his brothers are Azagon Lacroix and Baron Piquant and he is the husband of Maman Brigitte. Together, they are the guardians of the past, of history and, heritage. Baron Samedi is usually depicted with a top hat, black tail coat, dark glasses, and cotton plugs in the nostrils, as if to resemble a corpse dressed and prepared for burial in the Haitian style. He is frequently depicted as a skeleton (but sometimes as a black man that merely has his face painted as a skull), and speaks in a nasal voice. The former President-for-Life of Haiti, François Duvalier, known as Papa Doc, modeled his cult of personality on Baron Samedi; he was often seen speaking in a deep nasal tone and wearing dark glasses.He is noted for disruption, obscenity, debauchery, and having a particular fondness for tobacco and rum. Additionally, he is the loa of resurrection, and in the latter capacity he is often called upon for healing by those near or approaching death, as it is only the Baron that can accept an individual into the realm of the dead.Baron Samedi spends most of his time in the invisible realm of vodou spirits. He is notorious for his outrageous behavior, swearing continuously and making filthy jokes to the other spirits. He is married to another powerful spirit known as Maman Brigitte, but often chases after mortal women. He loves smoking and drinking and is rarely seen without a cigar in his mouth or a glass of rum in his bony fingers. Baron Samedi can usually be found at the crossroads between the worlds of death and the living. When someone dies, he digs their grave and greets their soul after they have been buried, leading them to the underworld"  
    },
    {
        title: "Bigfoot",
        topic: "Bigfoot",
        mainImg: TBD,
        secondaryImg: TBD,
        url: "/cryptids/:id",
        first_sighting: "Up to 1,000,000 years ago",
        last_sighting: "Present",
        continent: "All",
        country: "All",
        sighting_location:"Remote lush forests in mountainous regions of the world",
        source: "https://cryptidz.fandom.com/wiki/Bigfoot",
        description:"A Bigfoot is a heavy, bipedal humanoid ape. It is believed that Bigfoot stands at around eight to ten feet tall--however the Hibagon stands at only four to five feet--and has long arms. It has dense fur, ranging in colors from red, to white, to brown. It has very large feet, which is why it is called Bigfoot. Some people believe that Bigfoot is the descendant of the prehistoric giant orangutan Gigantopithecus, whereas others think it descended from prehistoric homininds such as a Neanderthal Man or Australopithecus. Some sightings of Bigfoot can be traced back to bears"  
    },
    {
        title: "El Chupacabra",
        topic: "animalistic",
        mainImg: TBD,
        secondaryImg: TBD,
        url: "/cryptids/:id",
        first_sighting: "March 1995",
        last_sighting: "2013",
        continent: "North America",
        country: "Puerto Rico, United States, Mexico, Paraguay",
        sighting_location: "Remote Deserts in Southwestern North America, and jungles of Puerto Rico",
        source: "https://cryptidz.fandom.com/wiki/Chupacabra",
        description:"Their first known attacks were in March of 1995 in Puerto Rico. Eight sheep were discovered dead, each completely drained of blood. Investigators found three strange puncture wounds in the chests of the animals. Despite the odd circumstances, authorities could only attribute the killings to a known predator - a fox, perhaps. Others, however, recognized the similarities in these deaths to the enigmatic cattle mutilations which had been taking place in the American southwest with increasing regularity. The woman who first sighted the monster, Madelyne Tolentino, had an eyewitness description was the basis for the most famous drawing of the chupacabra in the world. In Canóvanas, about 30 citizens claimed to have seen the chupacabras, swearing that it had swooped down from the sky and leapt over treetops. It wasn't until November, 19, 1995 that a detailed description of chupacabras came from an eyewitness. On that autumn night in Puerto Rico, the creature struck again. Farmers awoke to a horrifying scene: dozens of turkeys, rabbits, goats, cats, dogs, horses and cows... dead, with no explainable cause. Just the mysterious markings left by the blood-drinking chupacabras.But in the north-central city of Caguas, a startled homeowner caught the world's first fleeting glimpse of the goat sucker. Described as having huge red eyes and hairy arms, the creature allegedly broke into the bedroom of the house through a window, tore apart a child's stuffed Teddy bear, and left a puddle of slime and a single piece of rancid meat on the windowsill before disappearing. "  
    },
    {
        title: "Jersey Devil",
        topic: "animalistic",
        mainImg: TBD,
        secondaryImg: TBD,
        url: "/cryptids/:id",
        first_sighting: "1735",
        last_sighting: "2009",
        continent: "North America",
        country: "United States",
        sighting_location:"New Jersey",
        source: "https://cryptidz.fandom.com/wiki/Jersey_Devil",
        description:"The Jersey Devil is a creature native to the Pine Barrens of New Jersey. It is often described as having hooves, a snake's tail, bat-wings and a head that looks something like a horse. While there are many stories detailing the origin of the Jersey Devil, sightings have been reported beginning in the 1700s and continuing on until the past decade. The creature is deeply rooted in folklore and legend in the area, and is still mildly popular in various media, from sports teams to video games. This Jersey Devil often glows, and it can breathe fire or poison water with its breath, both classic dragon characteristics. The Jersey Devil of folklore is also known as the Leeds Devil. Local residents trace its origin to a woman named Mother Leeds, the mistress of a British soldier who was suspected of being a witch. When she gave birth to her thirteenth child, she cursed it. The baby was born as a hairy creature and soon took to terrorizing the populace and eating children."  
    },
    {
        title: "Jersey Devil",
        topic: "animalistic",
        mainImg: TBD,
        secondaryImg: TBD,
        url: "/cryptids/:id",
        first_sighting: "1735",
        last_sighting: "2009",
        continent: "North America",
        country: "United States",
        sighting_location:"New Jersey",
        source: "https://cryptidz.fandom.com/wiki/Jersey_Devil",
        description:"The Jersey Devil is a creature native to the Pine Barrens of New Jersey. It is often described as having hooves, a snake's tail, bat-wings and a head that looks something like a horse. While there are many stories detailing the origin of the Jersey Devil, sightings have been reported beginning in the 1700s and continuing on until the past decade. The creature is deeply rooted in folklore and legend in the area, and is still mildly popular in various media, from sports teams to video games. This Jersey Devil often glows, and it can breathe fire or poison water with its breath, both classic dragon characteristics. The Jersey Devil of folklore is also known as the Leeds Devil. Local residents trace its origin to a woman named Mother Leeds, the mistress of a British soldier who was suspected of being a witch. When she gave birth to her thirteenth child, she cursed it. The baby was born as a hairy creature and soon took to terrorizing the populace and eating children."  
    },
]
